/* Source Generated By LXC - Compiler */
.text 
    .global _start 
.data 
    color_red: .ascii  "\033[1;31;40m"
    color_green: .ascii  "\033[1;32;40m"
    color_blue: .ascii  "\033[1;34;40m"
    color_brown: .ascii  "\033[1;30;40m"
    color_purple: .ascii  "\033[1;35;40m"
    y0: .ascii  "                 \n " 
    y0lent = .-y0
    y1: .ascii  " This Message Is RED\n " 
    y1lent = .-y1
    y2: .ascii  " This Message Is GREEN\n " 
    y2lent = .-y2
    y3: .ascii  " This Message Is BLUE\n " 
    y3lent = .-y3
    y4: .ascii  " This Message Is PURPLE\n " 
    y4lent = .-y4
    y5: .ascii  " This Message Is BROWN\n " 
    y5lent = .-y5
.text 
_start:	
    MOV R7, #4
    MOV R0, #1
    LDR R2, =y0lent
    LDR R1, =y0
    SWI 0
    MOV R7, #4
    MOV R0, #1
    MOV R2, #10
    LDR R1, =color_red
    SWI 0
    MOV R7, #4
    MOV R0, #1
    LDR R2, =y1lent
    LDR R1, =y1
    SWI 0
    MOV R7, #4
    MOV R0, #1
    MOV R2, #10
    LDR R1, =color_green
    SWI 0
    MOV R7, #4
    MOV R0, #1
    LDR R2, =y2lent
    LDR R1, =y2
    SWI 0
    MOV R7, #4
    MOV R0, #1
    MOV R2, #10
    LDR R1, =color_blue
    SWI 0
    MOV R7, #4
    MOV R0, #1
    LDR R2, =y3lent
    LDR R1, =y3
    SWI 0
    MOV R7, #4
    MOV R0, #1
    MOV R2, #10
    LDR R1, =color_purple
    SWI 0
    MOV R7, #4
    MOV R0, #1
    LDR R2, =y4lent
    LDR R1, =y4
    SWI 0
    MOV R7, #4
    MOV R0, #1
    MOV R2, #10
    LDR R1, =color_brown
    SWI 0
    MOV R7, #4
    MOV R0, #1
    LDR R2, =y5lent
    LDR R1, =y5
    SWI 0
    B _start

    MOV R7, #1
    SWI 0
